spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-guard?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: /kMO£P:q|5u0\0S4Cr[R
  expiration: 3600000