spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-guard?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: /kMOPqhdsjhsd83508594hjffjdslfskfjsljhsdkahfkdsf7349573793hdfkshfjfioe4843983483498503jfhdskjfdk5u00S4CrR
  expiration: 3600000